# Generated by Django 3.1.6 on 2021-03-01 16:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('email', models.CharField(max_length=64)),
                ('rating', models.IntegerField()),
                ('origination_address', models.CharField(max_length=64)),
                ('origination_city', models.CharField(max_length=64)),
                ('origination_state', models.CharField(max_length=2)),
                ('destination_address', models.CharField(max_length=64)),
                ('destination_city', models.CharField(max_length=64)),
                ('destination_state', models.CharField(max_length=2)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('taking_passengers', models.BooleanField(default=False)),
                ('seats_available', models.IntegerField(default=0)),
                ('vehicle_model', models.CharField(max_length=64)),
                ('phone_number', models.CharField(blank=True, max_length=60, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format: 05999999999', regex='^(05)\\d{9}$')])),
            ],
        ),
    ]
