# Generated by Django 3.1.6 on 2021-02-27 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='origination',
        ),
        migrations.AddField(
            model_name='person',
            name='destination_address',
            field=models.CharField(default='null', max_length=64),
        ),
        migrations.AddField(
            model_name='person',
            name='email',
            field=models.CharField(default='null', max_length=64),
        ),
        migrations.AddField(
            model_name='person',
            name='last_name',
            field=models.CharField(default='null', max_length=64),
        ),
        migrations.AddField(
            model_name='person',
            name='origination_address',
            field=models.CharField(default='null', max_length=64),
        ),
        migrations.AddField(
            model_name='person',
            name='origination_city',
            field=models.CharField(default='null', max_length=64),
        ),
        migrations.AddField(
            model_name='person',
            name='origination_state',
            field=models.CharField(default='ZZ', max_length=2),
        ),
        migrations.AddField(
            model_name='person',
            name='phone_number',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='person',
            name='rating',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='person',
            name='vehicle_model',
            field=models.CharField(default='null', max_length=64),
        ),
        migrations.AlterField(
            model_name='person',
            name='date',
            field=models.DateField(default='2021-01-01'),
        ),
        migrations.AlterField(
            model_name='person',
            name='destination_city',
            field=models.CharField(default='null', max_length=64),
        ),
        migrations.AlterField(
            model_name='person',
            name='destination_state',
            field=models.CharField(default='ZZ', max_length=2),
        ),
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(default='null', max_length=64),
        ),
        migrations.AlterField(
            model_name='person',
            name='time',
            field=models.TimeField(verbose_name='00:00'),
        ),
    ]
