# Generated by Django 3.1.6 on 2021-02-27 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='origination',
            new_name='destination_address',
        ),
        migrations.AddField(
            model_name='person',
            name='email',
            field=models.CharField(default='no_email', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='last_name',
            field=models.CharField(default='null', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='origination_address',
            field=models.CharField(default='null', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='origination_city',
            field=models.CharField(default='null', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='origination_state',
            field=models.CharField(default='ZZ', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='phone_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='rating',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='vehicle_model',
            field=models.CharField(default='null', max_length=64),
            preserve_default=False,
        ),
    ]
