# Generated by Django 3.1.6 on 2021-02-27 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0002_auto_20210227_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='origination_state',
            field=models.CharField(max_length=2),
        ),
    ]
