# Generated by Django 3.1.6 on 2021-02-27 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0002_auto_20210227_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='person',
            name='destination_address',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='person',
            name='destination_city',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='person',
            name='destination_state',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='person',
            name='origination_address',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='person',
            name='origination_city',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='person',
            name='origination_state',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='person',
            name='rating',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='person',
            name='time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='person',
            name='vehicle_model',
            field=models.CharField(max_length=64),
        ),
    ]
